# SQLite version 3.x
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
 adapter: postgresql
 encoding: unicode
 database: x_development
 pool: 5
 username: stuarthenry
 password:

test:
 adapter: postgresql
 encoding: unicode
 database: x_test
 pool: 5
 username: stuarthenry
 password: